name: forge
description: >
  Dart wrapper of the Forge library for TLS.
version: 0.0.1
author: Nat Burns <nbaccount@burnskids.com>
homepage: https://github.com/burnnat/forge.dart
dependencies:
  js_wrapping: ^0.1.2
  quiver: ^0.21.3
dev_dependencies:
  browser: any
  js_wrapping_generator:
    git: git://github.com/burnnat/dart-js-wrapping-generator.git
  unittest: any
environment:
  sdk: ">=1.8.3 <2.0.0"
