name: forge
description: >
  Dart wrapper of the Forge library for TLS.
version: 0.0.1
author: Nat Burns <nbaccount@burnskids.com>
homepage: https://github.com/burnnat/forge.dart
documentation:
dependencies:
  js_wrapping: any
  quiver: any
dev_dependencies:
  browser: any
  js_wrapping_generator:
    git: git://github.com/burnnat/dart-js-wrapping-generator.git
  unittest: any
